### ISSUE TITLE
Bug in installer script

### ISSUE THREAD

**Issue by renefritze** [veraPDF/veraPDF-library#1021]
The linux installer script in the current release 1.12 zip does not forward command line args to the actual java command. As such using the XML description in a scripted install is currently impossible.

**Comment by renefritze** [comment]
On a sidenote: the https://github.com/veraPDF/veraPDF-apps repository does not mention where to report bugs explicitly, so I had to guess it's this one.

**Comment by carlwilson** [comment]
Hi @renefritze thanks very much for logging the issue and the matching fix. We're merging PRs and closing issues for an upcoming 1.14 release in June. This will be officially fixed in that release, I'll also review the READMEs on the other projects, we've only recently shut off the other issue trackers.
