### ISSUE TITLE
Possibly missed error re "ToUnicode CMap format"

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-library#1085]
Build: 2020-06-05T09:06:00+02:00

Attached file is OK in VeraPDF, but not in 
https://www.pdf-online.com/osa/validate.aspx
which claims "The value of the key ToUnicode is invalid but must be compliant to the ToUnicode CMap format."

I don't know who is right.
[Testdok.pdf](https://github.com/veraPDF/veraPDF-library/files/4736824/Testdok.pdf)

The file was created with LibreOffice 5.4.

**Comment by bdoubrov** [comment]
The issue with this ToUnicode CMap is the incorrect use of the **defineresource** PostScript operator, which is written as **define resource** . 

This is a known issue of LibreOffice export to PDF/A-1a, which, I think was fixed in LibreOffice 6.0: https://www.filehorse.com/download-libreoffice-64/33918/change-log/
