### ISSUE TITLE
WARNING: Type 1 fonts in PFB format are not permitted

### ISSUE THREAD

**Issue by Corvwyn** [veraPDF/veraPDF-library#1118]
I'm getting one warning and an error when running PDF/A-1b validation using veraPDF. Apache Preflight does not show any warnings, and indicates that this is a valid PDF/A-1b. Does Apache Preflight lack proper font validation?

Here are the warnings/errors:
"WARNING: Type 1 fonts in PFB format are not permitted"

"The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, except when the fonts are used exclusively with text rendering mode 3"

This warning seems to say that type 1 fonts in PFB format are never permitted in PDF/A, is this true?

Here's a link to a simple PDF/A-1b file using the font:
https://www.dropbox.com/s/9ew8hipbl6js0cv/verapdf_pdfa1b.pdf?dl=0

**Comment by THausherr** [comment]
I'm with the PDFBox project but in such cases I'd assume VeraPDF is more likely to be correct 😂

PDF-Tools also considers it to be not conforming
https://www.pdf-online.com/osa/validate.aspx
Validating file "verapdf_pdfa1b.pdf" for conformance level pdfa-1b
The embedded font Arial is corrupt and needs to be repaired.
The document does not conform to the requested standard.
The document contains fonts without embedded font programs or encoding information (CMAPs).
The document does not conform to the PDF/A-1b standard.

**Comment by Corvwyn** [comment]
Ah, ok. Thanks for the info @THausherr .

I remember using various online PDF/A validators, including this one some time ago, and not getting an error with the same font. I guess there might have been changes to PDF-Tools since that time, or maybe I didn't use PDF-Tools after all.

I still wonder if Type 1 fonts in PFB format are always incompatible with PDF/A though.

**Comment by bdoubrov** [comment]
It's not about PDF/A, but about PDF 1.7 (and now also PDF 2.0). Both ISO 32000-1 and 32000-2 provide detailed list of font formats that can be embedded into PDF. And PFB is not there.

**Comment by Corvwyn** [comment]
Interesting. That's good to know. It's definitely a good idea to stick to non-PFB fonts then.

So it would be technically valid to use PFB fonts in a PDF/A-1b of version PDF 1.6 then, even though non-PFB fonts would be preferrable.

Thanks for your answer.

**Comment by bdoubrov** [comment]
Sorry for being not very clear. **None of PDF specifications**, including earlier ones, mentions PFB fonts. I mentioned PDF 1.7 and PDF 2.0 mainly because these are the only ISO versions of PDF specification. 

PFB is a special packaging format for Type1 fonts. It is a fairly simple technical task to "unpackage" the font by removing extra binary markers introduced by PFB package. This is what normally a PDF processor implements when embedding such fonts into PDF. Embedding PFB files as is leads to the violation of the standard. Although most of the font libraries are flexible enough to accept PFB files. But this doesn't make PDF files compliant to the specification.

**Comment by Corvwyn** [comment]
Ok, got it. Thanks for the clarification. Your answers have been very useful.
