### ISSUE TITLE
Check for updates in the GUI via Maven central

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1240]
Choosing the menu item Help->Check for updates...  in the veraPDF GUI results in an error message "Update service not available"

**Comment by carlwilson** [comment]
This is caused by the use of a Jenkins build URL that's proved to be ephemeral. We need a permanent URL and a way of keeping it current and a better solution might use Maven central to work out what the latest version is. A Maven solution might be easy, is this worth worrying about for the 1.20.2 patch release?

**Comment by bdoubrov** [comment]
I'd prefer to minimize changes in the 1.20.2 patch. So, I suggest to wait with this issue till 1.22

**Comment by alexreg** [comment]
Good to know this is being worked on. Is there a temporary solution that allows the latest version to be queried, though? Even manually?

**Comment by alexreg** [comment]
@bdoubrov The least difficult thing may actually be to have the Homebrew formula check for the greatest even-numbered version (tag). The only thing in the way of that now is the `v2.x` tags... but those are obsolete, right? If we could remove them, then that would be perfect, otherwise I can try to find a work-around.

**Comment by bdoubrov** [comment]
@alexreg I've just deleted the v2.x.x tags from veraPDF-apps repo.

**Comment by alexreg** [comment]
@bdoubrov Actually, those tags still exist unfortunately... maybe they only got deleted locally?

**Comment by carlwilson** [comment]
Hi @alexreg, I've now "aggressively" deleted the `v2.*` tags from the main repos and the jenkins versions which @bdoubrov identified as the source of the issue. A better solution to the updater will be along in the next release but not a 1.20 patch.

**Comment by bdoubrov** [comment]
http://jenkins.openpreservation.org/job/veraPDF-apps/lastStableBuild/api/xml redirects now to the correct latest release build info

**Comment by bdoubrov** [comment]
One other way of getting the latest build info is to check for the latest release of `veraPDF-apps` at Maven central.

**Comment by alexreg** [comment]
@carlwilson @bdoubrov Thank you both. Now that the tags are gone, the "livecheck" for the Homebrew formula works nicely — so I'll probably just use that for now. Good to know about the alternative approaches too, however.

**Comment by bdoubrov** [comment]
Added the correct functionality to the latest veraPDF release 1.26. However, it will become useful for the end users only when the next update is available
