### ISSUE TITLE
PDF/UA 7.18.1

### ISSUE THREAD

**Issue by a20dev** [veraPDF/veraPDF-library#1285]
The attached document fails the test for clause 7.18.1, but all fields have a TU entry.

veraPDF 1.22.3 and 1.23.3.
[a-30.pdf](https://github.com/veraPDF/veraPDF-library/files/9607313/a-30.pdf)

**Comment by bdoubrov** [comment]
Thanks for submitting this issues.

There seems to be indeed a bug in retrieving the value of the TU entry for Widget annotations. Currently, if the Widget annotation dictionary contains a Parent key, the value of this Parent entry is treated as a part form field for this Widget annotation. However, this Parent entry may also mean just the parent from field in the hierarchy of the interactive forma fields, as in this attached document.

To be fixed in one of the nearest dev versions.

**Comment by georgetarazevich** [comment]
Checked with v. 1.23.25

**Comment by MaximPlusov** [comment]
Included into release 1.24
