### ISSUE TITLE
Latest 1.26.x artefacts not available on maven

### ISSUE THREAD

**Issue by dgt-amexio** [veraPDF/veraPDF-library#1466]
Hello,

I am relying on verapdf-model to validate PDF/A documents processed by an in-house application.
And I am currently facing issues when attempting to update my maven dependency org.verapdf:validation-model to 1.26+ 

Seems that version **1.26.2** has not been published on maven (see [here](https://mvnrepository.com/artifact/org.verapdf/pdfbox-validation-model-jakarta))
Could you kindly check ?

Kind regards
Denis

**Comment by bdoubrov** [comment]
The latest versions of artifacts seem to be correct on maven. It is `1.26.1` except for veraPDF Application, which is `1.26.2` due to some technical reasons related to Jenkins failure.  

 In any case the correct latest maven version is `1.26+` for all veraPDF dependencies.

I also see that you refer to `pdfbox-validation-model-jakarta`. Its latest version is also 1.26.1. However I note that PDFBox based parser will be deprecated starting from version 1.30. So, I recommend you trying to switch to `validation-model-jakarta`, if you use Jakarta version or just `validation-model` otherwise.

**Comment by dgt-amexio** [comment]
Hello Boris, 

Thx for your feedback and for the `pdfbox-validation-model-jakarta` artefact. Was an error of mine when finidng the link to introduce in my post, my impelemntation already relies on `validation-model-jakarta`

Kind regards
Denis
