### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#51]
Following the instructions in the readme, the software failed to build on my system (Linux Mint). Full mvn output is here:

<https://gist.github.com/bitsgalore/60c1c12d72cbe25fc3af>

I'm using the packages `maven2` and Oracle JDK 7; also tried with OpenJDK 7, but that's  giving me similar results.

(Should add that I know next to nothing of Java, so maybe I'm just doing something wrong).

**Comment by bdoubrov** [comment]
Hi Johan,

 

Thanks a lot for your feedback. Indeed, the builds fail at the moment due to the failure of integration tests (this is normal as we are doing a kind of test-driven development).

 

We’ve updated build instructions to skip them: https://github.com/veraPDF/veraPDF-library . Please let us know if you still get build errors.

 

Best regards,

Boris

**Comment by bitsgalore** [comment]
Hi Boris,

Thanks for that, I followed your updated instructions and it now builds!

Cheers,

Johan
