### ISSUE TITLE
Vera PDF testing with Archives NZ Born-Digital 'Preservation Masters'

### ISSUE THREAD

**Issue by ross-spencer** [veraPDF/veraPDF-library#549]
Posting on behalf of Archives New Zealand and @andreakb testing of Vera PDF on our 49 PDF Preservation Masters.

Speaking to @carlwilson on the last OPF call he suggested we upload the XML results from these as a zip to be put through further tests at Vera PDF HQ.

Obviously with 49 PDF we can't really test scale or performance, but these 49 should be useful from a preservation perspective as they are the most valuable PDFs in our collection being entirely born-digital.

The PDFs are also available to be downloaded by the public if there is any further need. We're happy to perform further testing too, and so the links are only here in the attached XLS as an FYI or if you're interested.

Keen to keep the dialog going. Please do let me know if this isn't the right project to attach these too, and let us know as well what else you might need from us so that we can help improve the tool.

[verapdf-0136output.zip](https://github.com/veraPDF/veraPDF-library/files/237865/verapdf-0136output.zip)

[PDF_PMs_GDA.xlsx](https://github.com/veraPDF/veraPDF-library/files/237866/PDF_PMs_GDA.xlsx)

**Comment by bdoubrov** [comment]
Run veraPDF 0.14 on the test files. The results are consistent with other PDF/A validators except for several cases:
- veraPDF does not report the presence of compressed objects in PDF/A-1. Strictly speaking this is violation of PDF 1.4 specification, not the ISO 19005-1. But as other validators report his as an error, this will also be added to veraPDF PDF/A-1b and PDF/A-1a validation profiles
- there is a known issue #547 with time zone handling in PDFBox, which is already fixed and will be included into the next veraPDF release
- there seem to be a disagreement whether all Metadata streams in PDF/A-1 documents shall be uncompressed, or this requirement concerns only the document level metadata. This issue was discussed on veraPDF TWG and resolved to require all Metadata streams to be uncompressed. This is how veraPDF validates this now
- another ambiguity still in discussion at veraPDF TWG is whether ExtGState dictionary shall be validated when it is referenced in the content stream, or when its parameters are really used for rendering. In several files the transparency alpha with value other than 1.0 is present in ExtGState, but never actually used for rendering
- two more cases when veraPDF reports an error on unembedded fonts to be investigated separately. Looks like some embedded fonts are not fully correct, and this results in this error message

**Comment by bdoubrov** [comment]
[PDF_PMs_GDA - Test result.pdf](https://github.com/veraPDF/veraPDF-library/files/279619/PDF_PMs_GDA.-.Test.result.pdf)

**Comment by ross-spencer** [comment]
Thanks Boris,

Here are the latest outputs from 0.14 from @andreakb for you to verify your results against. If you do create the same results PDF - we did find that really useful. 

[archives-nz-verapdf-0143output.zip](https://github.com/veraPDF/veraPDF-library/files/283511/archives-nz-verapdf-0143output.zip)

Cheers,

Ross
