### ISSUE TITLE
Crashing with OutOfMemoryError Exceptions

### ISSUE THREAD

**Issue by david-russo** [veraPDF/veraPDF-library#588]
Below are a sample of files which I've found to cause veraPDF to crash, throwing [OutOfMemoryError exceptions](https://github.com/veraPDF/veraPDF-library/files/455159/problematic-pdf-links-and-details.txt).
1. http://access.bl.uk/item/viewer/ark:/81055/vdc_00000001585E (91 mb)
2. http://access.bl.uk/item/viewer/ark:/81055/vdc_000000025A58 (185 mb)
3. http://access.bl.uk/item/viewer/ark:/81055/vdc_0000000156C0 (262 mb)
4. http://access.bl.uk/item/viewer/ark:/81055/vdc_000000025A16 (301 mb)
5. http://access.bl.uk/item/viewer/ark:/81055/vdc_000000037386 (425 mb)
6. http://access.bl.uk/item/viewer/ark:/81055/vdc_000000037500 (781 mb)

The crashes become particularly problematic when attempting to process files in batches. The crash leaves any remaining files unprocessed, with no indication of which file it choked on. I'd expect veraPDF to record its failure in the offending file's report instead of crashing, allowing it to continue with the remaining files.

veraPDF 0.20.3 CLI
Windows 7 (64-bit)
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by bdoubrov** [comment]
The latest release veraPDF 0.22.1 improves memory management and provides more user-friendly OutOfMemoryError handling along with instructions how to increase the JVM memory.

In particular, increasing the JVM memory to 4Gb allows to process all above test files. 

We still keep this issue open and will try to implement for robust batch processing.

**Comment by david-russo** [comment]
Hi Boris, thanks for looking into this.

Solving the problem by increasing the memory doesn't sound like a complete solution to me,
since it's predicated on the user still having to experience the problem, and even outside of batch processing I don't think crashing is an expected exit condition for a user. 

Since there's no limit to how large the contents of a PDF can be, it's easy to imagine a scenario where the resources necessary to complete validation might not exist. This being the case, it would seem prudent to include some heuristics which could allow veraPDF to recognize when it may not have the resources to finish processing a file and bow out gracefully, leaving a report.

**Comment by DuffJohnson** [comment]
> Since there's no limit to how large the contents of a PDF can be, it's easy to imagine a scenario where the resources necessary to complete validation might not exist. This being the case, it would seem prudent to include some heuristics which could allow veraPDF to recognize when it may not have the resources to finish processing a file and bow out gracefully, leaving a report.

I’ll ask what is probably a foolish question… would it be possible to expose a choice in memory allocation to the user as an option? 

If possible, it would imply that it’s the user’s responsibility to accommodate the files they’re trying to process. If they want to run crazy files on a puny box, that’s their problem.

If this is possible, then the “bow out gracefully” message could advise the user on how to address the problem.

Duff.

**Comment by david-russo** [comment]
I believe that's essentially how it works in 0.22.1: veraPDF prints a message after an OutOfMemory crash explaining how to provide more memory to the application. This still requires the user to restart the application after each crash, and doesn't include information on which file caused the crash. (Correct me if I'm wrong.)

I agree that it's up to the user to supply a powerful enough system to successfully process such files. I'm only suggesting that when the system does lack the resources, the application detects it and handles it in the same manner as it currently handles other failures: abort processing the problematic file and generate a report containing the error details. This would allow veraPDF to continue validating any remaining files, and provide the user with information on which files failed processing and why.

**Comment by bdoubrov** [comment]
This is exactly the reason why we want to keep this issue open for now. The idea is indeed to report the insufficient memory error in the report for a single file and proceed further when running batch validation.

**Comment by carlwilson** [comment]
I'll add my thoughts. Memory allocation in Java is a little painful as you have to assign it to the JVM at start time. This makes Duff's option suggestion more work than it appears because the parameter parsing is done in Java. This means that by the time we parse the parameters it's already too late, the memory is set. Regarding David's suggestion, the problem here is that if you allow the OOM exception to occur the JVM / program isn't guaranteed to continue running without problems.

There are a few options open to us:

- better memory management in the parser / validation model, we'll be working on this armed with memory profiler and test files;
- trying the simplest solution:
  * catch OOM exception in CLI batch loop;
  * report file as a failure due to lack of resources;
  * force the Java GC to run and free memory; and
  * continue with the next fille.
  * we could test the solution by ensuring that files processed following a memory bow out result in identical validation and feature reports as when the files are processed singly.
- we take a little time to look at using threads with a little isolation, either through Java's internals or by introductions a resource cache that's smaller than available resources. If a thread exhausts it's resources it shouldn't affect the rest of the code.

I suggest we try all of these as multi-threaded processing is desirable.

**Comment by david-russo** [comment]
Don't feel obliged to consider the simplest solution on my behalf — I certainly don't recommend rolling the die by trying to carry on from an OOME exception. I was thinking more along the lines of performing some kind of precalculation of required resources before committing to them, but I'm entirely unfamiliar with where the problem lies, and the last option already sounds more robust than what I was thinking.
