### ISSUE TITLE
Validation question

### ISSUE THREAD

**Issue by Ta1Nur** [veraPDF/veraPDF-library#613]
Greetings from City of Helsinki, Finland
We started to use veraPDF for validation this year in Spring 2016.

I hope that my question is suitable for this GitHub channel, even though it is not actual veraPDF issue. For future questions you can advice if veraPDF has something like support forum for these kind of issues.

My questions related to my case
Can you explain why veraPDF and Preflight validates differently? Can you give a hint, how this veraPDF validation error can be fixed "OrderContainAllOCGs"?

My case - Attached file created
- Saved to pdf-file (1.7) with Bentley CAD 
Creator Tool: MicroStation 8.11.9.459 by Bentley Systems, Incorporated
Producer: Adobe PDF Library 9.0

- Saved to PDF/A-2b with PDF-XChange Editor Plus Version 6.0 (Build 317.1) (Apr 19 2016;11:33:03)

- Validated with veraPDF version 0.20
ERROR 
specification="ISO_19005_2" clause="6.9" testNumber="3" 
DESCRIPTION "If an optional content configuration dictionary contains the Order key, the array which is the value of this Order key shall contain references to all OCGs in the conforming file." 
TEST doesOrderContainAllOCGs == true 
MESSAGE Not all optional content groups are present in the Order entry of the optional content configuration dictionary

- Validated also with Adobe Acrobat Pro DC  2015 version 2015.006.30033
Preflight PDF/A-2b validation -> No Problems Found

Attachment
[0851_6_picture-layers_PDFA-2b.PDF](https://github.com/veraPDF/veraPDF-library/files/561745/0851_6_picture-layers_PDFA-2b.PDF)

**Comment by bdoubrov** [comment]
I think the issue here is in a slightly ambiguous requirmement of PDF/A-2: "If an optional content configuration dictionary contains the Order key, the array which is the value of this Order key shall contain references to *all OCGs in the conforming file.*"

There are many optional content groups defined in your document (see /OCGs entry in the /OCProperties dictionary in the Catalog), which apparently not used anywhere in the page content.

And these "phantom" OCGs are not included into the /Order array of the default configuration dictionary defining the visibility of the groups. This is exactly what veraPDF complains about.

In more detail, the ISO 32000-1 defines the /Order array as: "An array specifying the order for presentation of optional content groups in an interactive PDF processor’s user interface." And to prevent any "hidden for the user" optional content groups the PDF/A-2 standard requires that this /Order array includes all OCGs of the document.

The only question is whether *all OCGs of the document* means all OCGs defined in the document catalog, or all OCGs actually used in the page description.  I'll try to clarify this at our next expert meenting.

**Comment by Ta1Nur** [comment]
I'm very pleased to hear that you take this issue to your next expert meeting. I will wait what is your resolution. Thanks a lot.

**Comment by bdoubrov** [comment]
Just to confirm that the Technical Workinf Group on PDF/A validation confirmed the above logic: all OCGs of the document means all OCGs defined in the document catalog. 

This is how it isimplemented in the latest release. So, I'm closing this issue for now.

**Comment by Ta1Nur** [comment]
Thank you for confirming this, we will continue investigate issue from MicroStation pdf settings.
