### ISSUE TITLE
Installed under Linux, but cannot invoke the programme

### ISSUE THREAD

**Issue by ruddyconsult** [veraPDF/veraPDF-library#715]
I have installed your programme under Linux (Ubuntu 14.04). I succeeded despite the small error on [this page](https://github.com/veraPDF/veraPDF-library#install-from-zip-package): 
java - jar
should read
java -jar

However I did receive some error messages.

After installation I saw the GUI.
Now however I cannot invoke the programme using the command listed in the documentation:
● on Mac OSX and Unix systems: verapdf-gui

**Comment by ruddyconsult** [comment]
OK, I have started the programme by clicking on the file verapdf-gui in my file manager.

However, my first attempt to validate a document was disappointing. I chose your very own:
File:	/home/thomas/verapdf/documents/veraPDFPDFAConformanceCheckerGUI.pdf
Validation Profile:	PDF/A-1B validation profile
Compliance status: 	Failed 

Can this be correct?

**Comment by carlwilson** [comment]
Hi @ruddyconsult thanks for getting in touch, I've fixed the typo that you pointed out. I think that your problem is that you'll need to add the path to the script file, that is instead of `verapdf`, you'll need to type `~/verapdf/verapdf` where `~` is shorthand for your home directory. This assumes that you installed veraPDF to the default directory. A more general form is `<verapdf-install-dir>/verapdf`. If you don't want to type this every time then you can add aliases by issuing these commands:

    echo "alias verapdf='~/verapdf/verapdf'" >> ~/.bash_aliases
    echo "alias verapdf-gui='~/verapdf/verapdf-gui'" >> ~/.bash_aliases

Then you can use `verapdf` and `verapdf-gui` as commands. Again these assume that you've installed veraPDF to the default location.

Regarding the conformance of the documentation PDF, this was created from a Google Doc and is just a plan PDF NOT a PDF/A and the result is correct.

I hope this answers your questions and thanks for the feedback.
