### ISSUE TITLE
some findings for veraPDF

### ISSUE THREAD

**Issue by Chlara** [veraPDF/veraPDF-library#750]
Hi,

The nestor Format Group is currently benchmarking some PDF/A validators (https://github.com/nestorFormatGroup/PdfaValidationBenchmarking). We are still working on that, but we have already some findings for veraPDF:

- v1.2.1 took more than 9 hours to validate 2980 Files, v1.4.1 still takes more than 6 hours --> there’s improvement, but other validators take only between 13 minutes and 2 hours
- veraPDF 1.4.1 disagrees with the other 3 validators in 11.81% (352 files) of all test files 
--> In 210 files veraPDF 1.4.1 finds the error 6.2.11.5-1 whereas all other validators claim those files are valid. Please review the error 6.2.11.5-1 (is it really a PDF/A restriction or is it a user defined additional check?)
--> In 34 files veraPDF 1.4.1 finds the error 6.3.6-1 whereas all other validators claim those files are valid. Please review the error 6.3.6-1 (is it really a PDF/A restriction or is it a user defined additional check?)
- The Message “{path} PDF/A Validation” was written 103 times in the log, often in parallel to an “Out of Memory Exception” message in the console. Maybe veraPDF could improve the message (ex. ERROR {path} Out of Memory Exception)?

Thanks,
Chlara

**Comment by bdoubrov** [comment]
Hi Chlara,

Thanks a lot for excellent benchmarking results. A few immediate comments:

- As far as I can see, 6.2.11.5-1 and 6.3.6-1 are the same rule, but the first one is forPDF/A-2 and 3 and the second is for PDF/A-1. There has indeed been a font parsing issue in the 1.4.1 release, which might have resulted in so many files reporing this failed rule. It was fixed in the hot fix 1.4.6 (http://downloads.verapdf.org/rel/1.4/verapdf-1.4.6-installer.zip). I wonder if you could rerun the tests with this version?

- Just to double check, do you use the greenfield version for tests, that is the one that does not have PDFBox in the installer name? I recall that we keep releasing two versions in parallel, one based on PDFBox parser, and another based on our newly developed greenfield parser. The performance may differ considerably between these two versions.

- What was the test environment use used? As veraPDF is written in Java, it is very sensitive to the amout of memory available.

**Comment by bdoubrov** [comment]
I wonder if test files can be made available in some manner? We'd be really interested to investigate some of the results in more detail and probably do some performance measurements as well.

**Comment by Chlara** [comment]
Hi Boris @bdoubrov , 

I rerun the test with 1.4.6 ((http://downloads.verapdf.org/rel/1.4/verapdf-1.4.6-installer.zip). Both tested version 1.4.6 and 1.4.1 seems to be the greenfield versions because there is no PDFBox in the Installer name.

For the test I use my normal laptop: Windows 7 Enterprise, 32 Bit, 8.00 GB (3.41 GB usable) RAM and JRE 1.8.0_131 x86.

The “test files” are real files and cannot be made available (the most files are confidential). 

The results with 1.4.6:
* v1.4.6 took nearly 8 hours to validate 2980 Files
* veraPDF 1.4.6 disagrees with the other 3 validators in 11.74% (350 files) of all test files --> In 215 files veraPDF 1.4.6 finds the error 6.2.11.5-1 whereas all other validators claim those files are valid.  --> In 35 files veraPDF 1.4.6 finds the error 6.3.6-1 whereas all other validators claim those files are valid. 
* The Message “{path} PDF/A Validation” was written 43 times in the log, often in parallel to an “Out of Memory Exception” message in the console. 

I resume the version 1.4.6: It takes more time than 1.4.1 (6:26:28 -> 7:57:54). The Percentage of disagreement is still more than 11% and the errors 6.3.6-1 and 6.2.11.5-1 are the cause of that (92%). The Memory exception is better now (103 -> 43).

Is the glyph width (6.3.6-1 and 6.2.11.5-1) really a PDF/A restriction or should it be a user defined additional check? I know that it is very important that the width is correct but is it written in the specification (PDF or PDF/A)?

Thanks,
Chlara

**Comment by bdoubrov** [comment]
The glyph widths requirement is one of the font clauses in all PDF/A parts. And as far as I know all PDF/A tools check this as well.

If you can't share all test files, I wonder if you could still send us:
- 5-10 files with this glyph width (6.3.6-1 and 6.2.11.5-1) issue where other validators do not report it?
- 5-10 files which take most time to validate by veraPDF?

**Comment by Chlara** [comment]
I will try to send you some files.

**Comment by shem-sergey** [comment]
Hello, Chlara!
We analyzed test files that you have sent and found a bug in font program parsing. This problem is fixed in the last version.
Also we ran some tests concerning verapdf performance on file 978-3-86644-537-6_pdfa.pdf. Total processing time on my PC (Ubuntu 16.10, 64-bit, 8.0 GiB RAM, Intel® Core™ i5-4460 CPU @ 3.20GHz × 4) was 30-35 seconds. We find it reasonable for a 50 MB file. In the attachment you can see validation report.
[veraPDF-report.txt](https://github.com/veraPDF/veraPDF-library/files/1054783/veraPDF-report.txt)

**Comment by bdoubrov** [comment]
Hi Chlara, 

We have just released versio 1.6: http://downloads.verapdf.org/rel/1.6/verapdf-1.6.1-installer.zip 

We'd be really grateful, if you could rerun your tests on this version and send us again several files where you see veraPDF results differ from other validators and several files where the software crashes or takes too much time to validate.

**Comment by Chlara** [comment]
Hi @bdoubrov  and @shem-sergey 
Thanks for your work. That sound grate. I will start the test and send you the results tomorrow.
Chlara

**Comment by bdoubrov** [comment]
Closing this issue for now. @Chlara if you've got any more recent test results, we'd be very glad to consider them
