### ISSUE TITLE
Test succeeds for the wrong reason

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#756]
Validation of
veraPDF-corpus/PDF_A-1b/6.1 File structure/6.1.12 Implementation limits/veraPDF test suite 6-1-12-t10-fail-a.pdf
with veraPDF 1.4.7 fails as expected. However, veraPDF claims that the failure is due to a font being used but not embedded. In fact, the font is embedded. The test should fail due to a CID greater than 65535.

**Comment by shem-sergey** [comment]
The message that veraPDF shows is not about font not being embedded but about font glyph being missing. Clearly, this glyph that has CID value greater than 65535 is not present in font, so this message is correct.
However, the message about CID being greater 65535 should be output too, and this is going to be fixed in the upcoming release.
