### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#800]
veraPDF 1.7.19 does not check clause 6.11 of ISO 19005-2:2011.

**Comment by bdoubrov** [comment]
Our rule 6-11-t01 is supposted to check exactly this: https://github.com/veraPDF/veraPDF-validation-profiles/blob/integration/PDF_A/2b/6.11%20Document%20requirements/verapdf-profile-6-11-t01.xml

Do you have test files for this issue?

**Comment by a20god** [comment]
Here you are:
[6.11-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1088992/6.11-fail-1.pdf)

**Comment by shem-sergey** [comment]
There is a little problem with your file that caused veraPDF not to recognize Requirements in catalog. That is that requirements should be an array of dictionaries according to specification and your test file has just a single requirement dictionary.
However a look into PDF_A specification reveals that "The document catalog shall not contain the Requirements key", so that is indeed a bug of veraPDF.

**Comment by a20god** [comment]
There are probably more instances of this problem. ISO 19005 nearly everywhere prohibits existence of certain **keys** rather than entries of a certain type and name.
