### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#821]
These documents cause a java.lang.StackOverflowError exception:

[loop-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1108474/loop-1.pdf)
[loop-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1108495/loop-3.pdf)
[loop-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1108568/loop-4.pdf)

**Comment by bdoubrov** [comment]
Thanks, it is a bit pathological situation. But this should not result in any crashes.

**Comment by a20god** [comment]
loop-4.pdf in particular is nasty.

**Comment by a20god** [comment]
This one needs to be taken care of once you fix https://github.com/veraPDF/veraPDF-library/issues/820:

[loop-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1108589/loop-2.pdf)

**Comment by a20god** [comment]
Here's a slightly improved version of loop-3.pdf which adds the missing BBox entry:

[loop-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1108605/loop-3.pdf)

**Comment by a20god** [comment]
Note that there is no implementation limit for nested Form XObject streams!

**Comment by a20god** [comment]
Another one:

[loop-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1108709/loop-6.pdf)

**Comment by a20god** [comment]
Since https://github.com/veraPDF/veraPDF-library/issues/760 has been fixed, this document also causes a stack overflow:

[loop-7.pdf](https://github.com/veraPDF/veraPDF-library/files/1108749/loop-7.pdf)

**Comment by a20god** [comment]
And another loop causing a stack overflow in veraPDF:

[loop-fail-8.pdf](https://github.com/veraPDF/veraPDF-library/files/1113022/loop-fail-8.pdf)

Two object streams, the N entry of each living in the other one.

**Comment by a20god** [comment]
Here's a UseCMap loop that causes veraPDF 1.7.55 to run out of memory:

[loop-9.pdf](https://github.com/veraPDF/veraPDF-library/files/1127900/loop-9.pdf)

**Comment by BezrukovM** [comment]
loop-1.pdf fixed in https://github.com/veraPDF/veraPDF-parser/pull/257. It is now still throws an exception (cause of invalid pdf structure with cycle in page tree), but now it is our new parser exception "LoopedTreeException" and it handled correctly in model parser. So we will obtain generated validation report for this file which will tell us that there was an exception caused by page looping
loop-3.pdf (both of them), loop-4.pdf fixed in https://github.com/veraPDF/veraPDF-validation/pull/215
loop-7.pdf fixed in https://github.com/veraPDF/veraPDF-parser/pull/258 (contains the same logic as for loop-1.pdf)
loop-2.pdf and loop-6.pdf fixed in https://github.com/veraPDF/veraPDF-parser/pull/259 (contains the same logic as for loop-1.pdf with one exception: for validation we do not need to reach the bottom of form fields tree. So validation for loop-2.pdf worked fine without that PR, but features generation produced StackOverflowException. Now features will produce correct LoopedTreeException).

Files loop-fail-8.pdf and loop-9 has not been fixed yet.

**Comment by shem-sergey** [comment]
After fixes in https://github.com/veraPDF/veraPDF-validation/pull/216 verapdf doesn't crash on loop-fail-8.pdf and loop-9.pdf with exceptions.

**Comment by BezrukovM** [comment]
Founded new files with loops which cause a java.lang.StackOverflowError exception. Loops in trailers by Prev key:
[222.pdf](https://github.com/veraPDF/veraPDF-library/files/1228039/222.pdf)
[111.pdf](https://github.com/veraPDF/veraPDF-library/files/1228040/111.pdf)

**Comment by BezrukovM** [comment]
Files 222.pdf and 111.pdf fixed in https://github.com/veraPDF/veraPDF-parser/pull/328
(Now will throw LoopedException. This is correct behavior.)
