### ISSUE TITLE
PDF/A-1 6.1.5 and tab vs. space

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#892]
## Dev Effort
3D

## Description
This is not a veraPDF issue, I think veraPDF behaves correctly. But the behavior is a bit unexpected, so this is something the Validation TWG might be interested in.

Look at these two documents:
[6.1.5-pass-03.pdf](https://github.com/veraPDF/veraPDF-library/files/1217863/6.1.5-pass-03.pdf)
[6.1.5-fail-14.pdf](https://github.com/veraPDF/veraPDF-library/files/1217864/6.1.5-fail-14.pdf)
Both have a TAB (U+0009) in the Metadata property and a space (U+0020) in the Info dictionary.

The difference comes from one property being an XML attribute, the other being an XML element. For the former, Attribute-Value Normalization is applied, unlike for the latter. For the Info entries which correspond to XML attributes in Metadata, it's impossible to have a TAB in the value without violating 6.1.5.

Well, after finding out that ModDate "2017-08-09" does not match xmp:ModifyDate "2017-08-09", this isn't that big a surprise.

The question is: Is this really the behavior intented by the ISO 19005 committee? That is, did they choose attribute vs. element based on whether Attribute-Value Normalization is to be applied or not? Or is this just some unfortunate side effect?

**Comment by bdoubrov** [comment]
The ISO 19005-1 specification says:
> The value of the document information dictionary entries and their analogous XMP properties shall be
**equivalent**. For properties that map from the PDF text string type to the XMP Text type, value equivalence shall be on a character-by-character basis, independent of encoding, comparing the numeric ISO/IEC 10646-1 code points for the characters.

I guess the specification uses the word "equivalent" and not equal exactly because direct comparison ofexxentially different data types is not possible. The following explanation about the text case is yet another hint. 

The normalization of TAB to SPACE is a part of XML specification (https://www.w3.org/TR/2004/REC-xml-20040204/#AVNormalize). So, I believe in this case TAB in XMP values  _is equivalent_ to the space in the values of Info dictionary keys.

**Comment by a20god** [comment]
I tried to make veraPDF with --fixmetadata craete a Metadata property (stored in an attribute) containing a TAB, but I found out that --fixmetadata is a misnomer: it sets the Info dictionary from Metadata rather than vice versa.

**Comment by bdoubrov** [comment]
Well, this is by design -- veraPDF assumes that XMP values take precedence over Info dictionary. But this is not the first time we get a request to make it an option: whether to sync XMP package from the Info dictionary or vice versa. So, we'll raise the priority of this one.

**Comment by carlwilson** [comment]
This still feels like an open issue and would probably require a specific option to control. It's interesting from a preservation POV also.

**Comment by bdoubrov** [comment]
yes, this is still open. We can raise the priority and include it in the next release

**Comment by bdoubrov** [comment]
TAB and SPACE are two different (Unicode) characters. As Info strings and the corresponding XMP strings are compared for comparison of Unicode characters, the use of SPACE in XMP and TAB in Info dictionary string will result in the validation error.
