### ISSUE TITLE
Test against conforming documents failed

### ISSUE THREAD

**Issue by itzbund** [veraPDF/veraPDF-library#923]
Hi,

i tested vera with greenfield an the Bavaria Testsuite (from PDFlib) with the result, that 20 conforming documents out of 58 are "nonCompilant".

some examples:
[bley.pdf](https://github.com/veraPDF/veraPDF-library/files/1394890/bley.pdf)
[2002_28.pdf](https://github.com/veraPDF/veraPDF-library/files/1394886/2002_28.pdf)
[braun_feudel.pdf](https://github.com/veraPDF/veraPDF-library/files/1394899/braun_feudel.pdf)
[paperG8_A1b.pdf](https://github.com/veraPDF/veraPDF-library/files/1394907/paperG8_A1b.pdf)

They are included in testcases in the pdfbox.

**Comment by itzbund** [comment]
I tested vera with pdfbox and there are 18 conforming documents that are tested as "nonCompilant".

example:
[vjs_05_Art05.pdf](https://github.com/veraPDF/veraPDF-library/files/1394985/vjs_05_Art05.pdf)

**Comment by itzbund** [comment]
a test against the isator Testsuite results in one conforming document wich is not expected

example:
[isartor-6-2-4-t01-fail-a.pdf](https://github.com/veraPDF/veraPDF-library/files/1395029/isartor-6-2-4-t01-fail-a.pdf)

**Comment by bdoubrov** [comment]
I wonder which version is used for tests here? 

Looking at the test results of 1.8 release against isartor test suite (see http://tests.verapdf.org/1.8/4/Isartor-1b/index.html ), I indeed see this one failing for the PDFBox-based version. But the greenfield version is OK. We'll investigate this in more detail. 

But I would recommend you switching to the Greenfield version, which has better performance and apparently does conform to Isartor test suite.

**Comment by bdoubrov** [comment]
veraPDF now treats the above 4 Bavaria files as valid. The issue was that it validated coordinates in the Destination array as reals. This has been discussed at TWG and clarified that even if coordinates are real numbers, they can be represented in PDF syntax as both Integer or Real, with different corresponding implementation limits. 

This new logic is available in dev version 1.13.26 and will be included into the next release version. 

The difference between PDFBox and GreenField version is treated separately in #956. 

So, I'm closing this issue for now.
