### ISSUE TITLE
veraPDF-library-1.12.1.tar.gz  seems to be veraPDF-library-1.10.2.tar.gz with new RELEASENOTES.md?

### ISSUE THREAD

**Issue by jschleus** [veraPDF/veraPDF-library#966]
Hmm, maybe I'm completely wrong but I have the impression that the new `veraPDF-library-1.12.1.tar.gz` is identical to  `veraPDF-library-1.10.2.tar.gz` with the exception of the file `RELEASENOTES.md` (that contains additional entries describing `Version 1.10 November 30, 2017`).

Also the modification date of all member files is `2017-11-30 13:55` but under
 https://github.com/veraPDF/veraPDF-library/releases
one found `Version 1.12 (May 9, 2018)`.

**Comment by carlwilson** [comment]
Hi @jschleus thanks for picking this up. At first this appeared slightly disastrous but on investigation the issue seems to be that the build tag added by our CI server is wrong. The released binary and the Maven releases are all up to date. I'll delete the erroneous tag, re-tag at the correct point, and then close this if that's OK.

**Comment by carlwilson** [comment]
corrected now, thanks for the keen eyes and happy that it's just a tagging error.

**Comment by jschleus** [comment]
Thanks, looks "much better" now ;-)
